export const videoData = [
  {
    id: "1",
    videoUrl: "https://vimeo.com/189877156",
    videoThumbnail: "",
    name: "Soccer Move A",
    check: "",
  },
  {
    id: "2",
    videoUrl: "https://vimeo.com/378024554",
    videoThumbnail: "",
    name: "Soccer Technique B",
    check: "",
  },
  {
    id: "3",
    videoUrl: "https://vimeo.com/45684011",
    videoThumbnail: "",
    name: "Soccer Drill C",
    check: "",
  },
  {
    id: "4",
    videoUrl: "https://vimeo.com/189877159",
    videoThumbnail: "",
    name: "Soccer Move D",
    check: "",
  },
  {
    id: "5",
    videoUrl: "https://vimeo.com/142997385",
    videoThumbnail: "",
    name: "Soccer Skill E",
    check: "",
  },
  {
    id: "6",
    videoUrl: "https://vimeo.com/11235525",
    videoThumbnail: "",
    name: "Soccer Technique F",
    check: "",
  },
  {
    id: "7",
    videoUrl: "https://vimeo.com/158142836",
    videoThumbnail: "",
    name: "Soccer Drill G",
    check: "",
  },
  {
    id: "8",
    videoUrl: "https://vimeo.com/93108362",
    videoThumbnail: "",
    name: "Soccer Move H",
    check: "",
  },
  {
    id: "9",
    videoUrl: "https://vimeo.com/200438528",
    videoThumbnail: "",
    name: "Soccer Skill I",
    check: "",
  },
  {
    id: "10",
    videoUrl: "https://vimeo.com/7378514",
    videoThumbnail: "",
    name: "Soccer Technique J",
    check: "",
  },
  {
    id: "11",
    videoUrl: "https://vimeo.com/172246962",
    videoThumbnail: "",
    name: "Soccer Move K",
    check: "",
  },
  {
    id: "12",
    videoUrl: "https://vimeo.com/117410011",
    videoThumbnail: "",
    name: "Soccer Skill L",
    check: "",
  },
  {
    id: "13",
    videoUrl: "https://vimeo.com/165441436",
    videoThumbnail: "",
    name: "Soccer Technique M",
    check: "",
  },
  {
    id: "14",
    videoUrl: "https://vimeo.com/171312770",
    videoThumbnail: "",
    name: "Soccer Drill N",
    check: "",
  },
  {
    id: "15",
    videoUrl: "https://vimeo.com/87276594",
    videoThumbnail: "",
    name: "Soccer Move O",
    check: "",
  },
  {
    id: "16",
    videoUrl: "https://vimeo.com/31097989",
    videoThumbnail: "",
    name: "Soccer Skill P",
    check: "",
  },
  {
    id: "17",
    videoUrl: "https://vimeo.com/869400057",
    videoThumbnail: "",
    name: "Soccer Technique Q",
    check: "",
  },
  {
    id: "18",
    videoUrl: "https://vimeo.com/840070246",
    videoThumbnail: "",
    name: "Soccer Drill R",
    check: "",
  },
  {
    id: "19",
    videoUrl: "https://vimeo.com/869397632",
    videoThumbnail: "",
    name: "Soccer Move S",
    check: "",
  },
  {
    id: "20",
    videoUrl: "https://vimeo.com/492872282",
    videoThumbnail: "",
    name: "Soccer Skill T",
    check: "",
  },
];
